// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client — tries service_role key first, then anon key.
// Use for admin operations in server functions that need to bypass RLS.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ANON_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function pickKey(): string | null {
  if (SERVICE_KEY) return SERVICE_KEY;
  if (ANON_KEY) return ANON_KEY;
  return null;
}

let cached: ReturnType<typeof createClient<Database>> | null = null;

function getClient(): ReturnType<typeof createClient<Database>> {
  if (cached) return cached;
  const url = SUPABASE_URL;
  const key = pickKey();
  if (!url || !key) {
    throw new Error('Supabase admin client unavailable (missing SUPABASE_URL or keys)');
  }
  cached = createClient<Database>(url, key, {
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });
  return cached;
}

// Server-side client: use service_role key if available, else anon key.
// Usage: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop) {
    return Reflect.get(getClient(), prop);
  },
});
